import type { Meta, StoryObj } from "@storybook/react"
import { DisclosureBadge } from "../../components/ui/disclosure-badge"

const meta: Meta<typeof DisclosureBadge> = {
  title: "AI / Conversation/DisclosureBadge",
  component: DisclosureBadge,
  parameters: { layout: "padded" },
  argTypes: {
    variant:  { control: "select", options: ["filled", "subtle", "ghost"] },
    size:     { control: "select", options: ["sm", "md"] },
    showIcon: { control: "boolean" },
    label:    { control: "text" },
  },
}

export default meta
type Story = StoryObj<typeof DisclosureBadge>

export const Subtle: Story = {
  name: "Subtle — default",
  render: () => <DisclosureBadge />,
}

export const Filled: Story = {
  name: "Filled",
  render: () => <DisclosureBadge variant="filled" />,
}

export const Ghost: Story = {
  name: "Ghost — inline prose",
  render: () => (
    <p className="text-sm max-w-lg">
      The following summary was prepared by an AI model <DisclosureBadge variant="ghost" label="AI" showIcon={false} />.
      Please review before sharing externally.
    </p>
  ),
}

export const AllVariants: Story = {
  name: "All variants",
  render: () => (
    <div className="flex flex-wrap items-center gap-4">
      {(["filled", "subtle", "ghost"] as const).map((v) => (
        <div key={v} className="flex flex-col items-center gap-1">
          <DisclosureBadge variant={v} />
          <span className="text-xs text-muted-foreground">{v}</span>
        </div>
      ))}
    </div>
  ),
}

export const Sizes: Story = {
  name: "Sizes",
  render: () => (
    <div className="flex flex-wrap items-center gap-4">
      <div className="flex flex-col items-center gap-1">
        <DisclosureBadge size="sm" />
        <span className="text-xs text-muted-foreground">sm</span>
      </div>
      <div className="flex flex-col items-center gap-1">
        <DisclosureBadge size="md" />
        <span className="text-xs text-muted-foreground">md</span>
      </div>
    </div>
  ),
}

export const InMessageContext: Story = {
  name: "In message bubble context",
  render: () => (
    <div className="max-w-2xl flex flex-col gap-1">
      <div className="flex items-start gap-2">
        <div className="flex-1 rounded-xl bg-muted px-4 py-3 text-sm">
          Q3 revenue grew 12% year-over-year, driven by strong enterprise sales and improved retention.
          The outlook for Q4 remains cautiously optimistic, with management guiding for continued double-digit growth.
        </div>
      </div>
      <div className="flex items-center gap-2 pl-4">
        <DisclosureBadge variant="subtle" size="sm" />
        <span className="text-xs text-muted-foreground">Review this before sharing</span>
      </div>
    </div>
  ),
}

export const CustomLabels: Story = {
  name: "Custom labels",
  render: () => (
    <div className="flex flex-wrap items-center gap-3">
      <DisclosureBadge label="AI summary" />
      <DisclosureBadge label="AI draft" variant="filled" />
      <DisclosureBadge label="Generated by Claude" variant="subtle" size="md" />
      <DisclosureBadge label="AI" variant="ghost" size="sm" showIcon={false} />
    </div>
  ),
}

export const Playground: Story = {
  args: {
    label:    "AI-generated",
    variant:  "subtle",
    size:     "sm",
    showIcon: true,
  },
}
