"use client"

import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "@/lib/utils"
import { Sparkles } from "lucide-react"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip"

// ─── Variants ────────────────────────────────────────────────────────────────

const disclosureVariants = cva(
  "inline-flex items-center gap-[var(--alias-spacing-inline-xs)] rounded-[var(--component-disclosure-dimension-radius)] select-none whitespace-nowrap",
  {
    variants: {
      variant: {
        /** Filled brand badge — use when AI content needs strong marking */
        filled: "bg-[var(--component-disclosure-color-bg)] text-[var(--component-disclosure-color-text)] px-1.5 py-0.5",
        /** Subtle ghost — use inline in prose or secondary positions */
        subtle: "border border-[var(--component-disclosure-color-border)] bg-[var(--component-disclosure-color-bg-subtle)] text-[var(--component-disclosure-color-text-subtle)] px-1.5 py-0.5",
        /** Minimal label-only, no background */
        ghost:  "text-[var(--component-disclosure-color-text-subtle)] px-0 py-0",
      },
      size: {
        sm: "text-[length:var(--alias-typography-caption2-font-size)] font-medium [&_svg]:size-2.5",
        md: "text-[length:var(--alias-typography-body-text3-font-size)] font-medium [&_svg]:size-3",
      },
    },
    defaultVariants: { variant: "subtle", size: "sm" },
  }
)

// ─── Props ───────────────────────────────────────────────────────────────────

export interface DisclosureBadgeProps
  extends React.ComponentProps<"span">,
    VariantProps<typeof disclosureVariants> {
  /** Label text — defaults to "AI-generated" */
  label?: string
  /** Tooltip explanation for screen readers and curious users */
  tooltip?: string
  /** Show the Sparkles icon */
  showIcon?: boolean
}

// ─── Component ───────────────────────────────────────────────────────────────

function DisclosureBadge({
  label    = "AI-generated",
  tooltip  = "This content was generated by an AI model. Review before use.",
  showIcon = true,
  variant,
  size,
  className,
  ...props
}: DisclosureBadgeProps) {
  const badge = (
    <span
      data-slot="disclosure-badge"
      aria-label={tooltip}
      className={cn(disclosureVariants({ variant, size }), className)}
      {...props}
    >
      {showIcon && <Sparkles aria-hidden="true" />}
      {label}
    </span>
  )

  if (!tooltip) return badge

  return (
    <Tooltip>
      <TooltipTrigger asChild>{badge}</TooltipTrigger>
      <TooltipContent side="top" className="max-w-[220px] text-xs text-center">
        {tooltip}
      </TooltipContent>
    </Tooltip>
  )
}

export { DisclosureBadge, disclosureVariants }
